export const cassettes = [
    {
      id: 1,
      title: "Cassette 1",
      artist: "Artist 1",
      year: 2021,
      genre: "Rock",
      textureUrl: "images/cassette-1.svg",
    },
    {
      id: 2,
      title: "Cassette 2",
      artist: "Artist 2",
      year: 2021,
      genre: "Pop",
      textureUrl: "images/cassette-2.svg",
    },
    {
      id: 3,
      title: "Cassette 3",
      artist: "Artist 3",
      year: 2021,
      genre: "Jazz",
      textureUrl: "images/cassette-3.svg",
    },
    {
      id: 4,
      title: "Cassette 4",
      artist: "Artist 4",
      year: 2021,
      genre: "Rap",
      textureUrl: "images/cassette-4.svg",
    },
    {
      id: 5,
      title: "Cassette 5",
      artist: "Artist 5",
      year: 2021,
      genre: "Country",
      textureUrl: "images/cassette-5.svg",
    },
    {
      id: 6,
      title: "Cassette 6",
      artist: "Artist 6",
      year: 2021,
      genre: "Classical",
      textureUrl: "images/cassette-6.svg",
    },
  ];